### ISSUE TITLE
NullReferenceException while creating new Pkcs12Store

### ISSUE THREAD

**Issue by Elikill58** [kerryjiang/BouncyCastle.Crypto#2]
I'm trying to use BouncyCastle.
On Java, it's works pretty well, but on C# I have a problem :
I create a new FileStream with valid information, then I run this method :
`new Pkcs12Store(fs, password.ToCharArray());`

And this is the error that I get :
```   at Org.BouncyCastle.Asn1.Pkcs.Pfx..ctor(Asn1Sequence seq) in D:\a\1\s\crypto\src\asn1\pkcs\Pfx.cs :line 20
   at Org.BouncyCastle.Pkcs.Pkcs12Store.Load(Stream input, Char[] password) in D:\a\1\s\crypto\src\pkcs\Pkcs12Store.cs :line 201
   at Org.BouncyCastle.Pkcs.Pkcs12Store..ctor(Stream input, Char[] password) in D:\a\1\s\crypto\src\pkcs\Pkcs12Store.cs :line 109
```

**Comment by Elikill58** [comment]
Fixed : I used 1.8.6.7 and not 1.8.5 or 1.8.8
